name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Prettier check
        run: npm run format:check --if-present

      - name: Lint (no warnings)
        run: npm run lint --if-present -- --max-warnings=0

      - name: Typecheck
        run: npx tsc -b --pretty false

      - name: Build
        run: npm run build
